### ISSUE TITLE
Attendance/Loot Dates One Day Ahead

### ISSUE THREAD

**Issue by sawprogramming** [sawprogramming/WoW-Raid-Manager#39]
This issue again.

**Comment by sawprogramming** [comment]
Hopefully fixed v2.3.0 by adding the new version of angular-ui and some changes in javascript to how the date is determined.

**Comment by sawprogramming** [comment]
Still not correct on a production version.

**Comment by Scabbrox** [comment]
Sorry to necro this issue but it's still there except it's now one day behind...  Basically if I select the date in the dashboard for an entire raid it usually works ok (I say usually as it actually put it one day ahead when I added Sunday's raid attendance after midnight in the early morning of the following day so might be a time-zone related issue?)  If however I add a player individually or edit an entry it drops to a date a day before the day I selected on the calendar pop-up and I need to do it twice for the change to take.  Either that or just select the following day and allow it to bug to previous day and leave it at that.

Weird behaviour either way.

**Comment by sawprogramming** [comment]
I tried to put something in to work around it. Let me know if you still experience the issue.

**Comment by Scabbrox** [comment]
> I tried to put something in to work around it. Let me know if you still experience the issue.

Just to be clear, the fix is only for this issue, not the other two?

Adding a new record works, but there is still the bug when you edit a record.  It backdates it one day even if you just open and select done or if you select the same day, it saves it as the day before.

Not seeing any difference on the other issues mentioned on the other bug reports.

**Comment by Scabbrox** [comment]
Short movie of what I mean here: https://youtu.be/ruIgXxTWbTQ

**Comment by RaefWolfe** [comment]
Tentatively, this appears to be fixed for me. All dates in both front-end modals and the attendance records appear as I have entered / saved them in the dashboard.
