### ISSUE TITLE
Unable to Import Characters

### ISSUE THREAD

**Issue by Scabbrox** [sawprogramming/WoW-Raid-Manager#45]
I'm getting the following error when trying to import characters.

I'm not sure if this project is supported any longer or if it no longer works but thought I'd give it a shot asking as it's the only solution out there for wordpress and it's a shame it doesn't work.

422

 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%u, %u, '11', '9', 'Scabbrox', 'draenor/3/88972035-avatar.jpg')' at line 2

**Comment by sawprogramming** [comment]
Thanks for the bug report!

Looked like WordPress changed how it handled some wildcards since I last used it. I just pushed changes that seemed to have fixed the issue. Install the new distribution and let me know if that works!

**Comment by Scabbrox** [comment]
Thank you very much getting to this so quickly!  I can confirm it now works so thanks a lot for getting it functional again.

One point, is there any reason why this plug-in isn't present in the list of Wordpress plugins when you type in a search?  I found it with a google search, but it's not on the list and so doesn't get any update notifications pushed (I deleted the old one and installed this one).  I'm sure you'd get a lot more guilds using it if it was more visible as there isn't anything else out there that does this.

Lastly, a feature request as I go about putting all my historic attendance data into the plug-in as we've just moved our guild website from and Enjin site to our own WP based site, but would it be possible to get the back/up and import function to recognise Mizus Raid Tracker output and thereby import entire raids for attendance a loot purposes instead of player by player?

I realise this might be a huge amount of work so if it is then my apologies, we'll get it input manually, just curious as importing from Mizus would open up the user base even more if it wasn't as big a deal to implement.

Either way, thanks for updating the plug-in!

_Edit:  I realise I must be missing something important as I am new to this plug-in but whilst I can find and use the admin panel fine, how do I access and display the user panel and the raid selection menu?  There do not appear in the admin section menu._

**Comment by sawprogramming** [comment]
It's not listed because I never looked into it; was just something I made for my guild back in the day. 

That feature would be too much work and I can't take that on, sorry!

Just now saw your edit! You show the user page by going to the 'Pages' section of WordPress' admin panel, selecting the page you want it to appear on, and choosing the 'Attendance' template. I didn't realize this wasn't in the documentation anywhere, I'll add it now!
