### ISSUE TITLE
Where do I view the front-end?

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#46]
I cannot for the life of me figure out how or where to view the front-end version of this plugin. I've extracted both the dev and production versions to my site with no luck. The admin area works fine from what I can tell.

I even tried adding the att-template.php to my regular template files and selecting it as a template for a page. That worked to display the barebones table, but absolutely none of the information was populated.

**Comment by RaefWolfe** [comment]
I figured out the issue. My current version of wordpress wasn't working with the templating file, which was for an outdated version of Wordpress. I'm not really familiar with how github works as far as adding to the code, but here is the solution:

Replace the "PageTemplater.php" file with this:

https://github.com/wpexplorer/page-templater/blob/master/pagetemplater.php

Replace Lines 77-79...

```
$this->templates = array(
	'goodtobebad-template.php' => 'It\'s Good to Be Bad',
);
```

with...

```
$this->templates = array(
	'../attnd-template.php' => 'Attendance');
);
```

Then, create a page and assign it the "Attendace" template. It should now auto populate :)

**Comment by sawprogramming** [comment]
Thanks for reporting! I went and updated the library used for this and it also worked with the version of WordPress I was using, so I committed the change.
