### ISSUE TITLE
Avatar Render inaccurate

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#47]
For anyone using this who noticed the avatars are broken or outdated.

In file: /scripts/app/user-ui/player-breakdown-modal.html

Line 8, replace:

`<img ng-src="http://us.battle.net/static-render/us/{{vm.BreakdownEntity.Icon}}" height="128" width="128"/>`

With:

`<img ng-src="http://render-us.worldofwarcraft.com/character/{{vm.BreakdownEntity.Icon}}" height="128" width="128"/>`

In accordance with this update:

https://us.battle.net/forums/en/wow/topic/20752046076

I also had to do the following, which you may not.

In scripts/app/user-ui/user-ui.controller.js

Line 81, Replace:

`templateUrl: plugin_url.app + '/user-ui/player-breakdown-modal.html',`

with:

`templateUrl: 'full URL of file location',`

**Comment by sawprogramming** [comment]
Thanks for reporting! I committed some changes to account for that update, and fixed a bug where EU characters wouldn't display images!
