### ISSUE TITLE
Uldir

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#48]
Now that BFA & Uldir has been released, there needs to be an update to the raid dropdown.

Battle for Azeroth released August 13th; Uldir released September 4th.

I added this information to DatabaseSeeder but it didn't seem to have any effect, so I assume there's a step I'm missing.

**Comment by sawprogramming** [comment]
I'll take a look at this this weekend!

**Comment by sawprogramming** [comment]
I pushed the commit to add the information. When you add stuff to that seeder:

1) Make sure the IDs follow in sequence and all the dates are updated and valid
2) Make sure the IDs in the RaidTierTable match those in the Expansion Table
3) After the new file/version is on your box, deactivate and reactivate the plugin for the seeder to run again.

**If the backup function still works, it's always a good idea to backup before updating!**

Let me know when it works for you so I can close the issue, and thanks again for the report!

**Comment by RaefWolfe** [comment]
I just didn't toggle the plugin on and off, that's what I was missing. Works a charm, thanks!
