### ISSUE TITLE
Attendance record not displaying graph and calendar misalignment on front end

### ISSUE THREAD

**Issue by Scabbrox** [sawprogramming/WoW-Raid-Manager#51]
May as well add the following issues as well whilst I'm here.

1.  The graph that is supposed to display when you click a player name is throwing an error every time.  It's also not respecting site or themes or colours or the general colour of the plug-in display and is hard to see.
![screenshot 2018-12-24 at 11 06 28](https://user-images.githubusercontent.com/35002130/50396785-5f67a080-076c-11e9-855a-5969d4951c14.png)

2.  The calendars on the From-To date selection clip outside the browser frame and some dates can't be selected.  Frame width makes no difference, does it on full screen on a 27" monitor too.
![screenshot 2018-12-24 at 11 10 52](https://user-images.githubusercontent.com/35002130/50396821-99d13d80-076c-11e9-8eae-bea60df0f8f0.png)

**Comment by sawprogramming** [comment]
I can't see this on my local machine; I tested on Firefox, Chrome, and Edge. 

Most likely another plugin or theme being used is loading afterwards and overwriting the styles. Which plugins and themes are you using?

**Comment by Scabbrox** [comment]
Oops, replied on the wrong report....

As I said on the other, Godlike Theme (NK) though heavily modified with a fair load of extra plugins.  Site here: weekend-warriors.net

I can grant you temporary admin access if you want to help tie it down.

If it's not the theme, it could be anyone of several.  Tried this on Safari and Chrome, doing it for me.  The attendance and loot page is public at : https://weekend-warriors.net/raid-attendance-loot/

**Comment by Scabbrox** [comment]
Plugins list.

[plugins.txt](https://github.com/sawprogramming/WoW-Raid-Manager/files/2707565/plugins.txt)

**Comment by Scabbrox** [comment]
Can confirm that the graph issue is only present on Safari (Mac).  It displays without the error message on Chrome (Mac).  The calendar clipping is present on both however.

**Comment by sawprogramming** [comment]
Thanks for the great bug report. It might not be something I can fix since both your theme and this plugin share the same CSS library for displaying stuff -- they just modified it and took priority.

**Comment by Scabbrox** [comment]
Just a suggestion, not sure if it's possible, but if the date fields were not right side aligned but rather left side, next to the raid tier pulldown menu then they wouldn't clip off the page on any theme.

I'd really like to get this plugin working for my guild but currently with the item tooltip display issue and the inability to select a from to date I can't really use it.

**Comment by sawprogramming** [comment]
Marking as helpwanted and wontfix just since it has to do with conflicting CSS and I don't know of any way to get around that.
