### ISSUE TITLE
Some character portraits not loading

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#54]
I can't seem to find a pattern. Some of these characters are very old; some are new; some of these characters have been race/name changed, some have not.

Not all the portraits on the modals work.

https://www.ministryofdefense.net/raiding/raid-attendance/

Quetzie works (old character, race-changed); Liv doesn't (old character; name-changed); Zuldrat doesn't (old character, no changes); Tiraffe does (old character, no changes); Pestis does (new character). 

All these characters exist and work within the armory.

**Comment by sawprogramming** [comment]
This was related to the same issue as the loot not showing. The API's security certificate changed and the PHP backend had some issues with it. Will be adding a fix soon.

**Comment by sawprogramming** [comment]
The fix is added, but I don't think it will apply automatically; I don't see anything in my code to go maintain those URLs. 

For any player with a problem, just go to the Edit menu for each player and save them as-is to trigger a refresh.
