### ISSUE TITLE
Attendance Record date selector  - wrong date style

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#55]
When I select an attendance record to edit, the date field autofills written in "YYYY-M-D" format. If I try to save (whether or not I make changes to the entry), the date field turns red as though I have not selected a date. When I click the calendar icon and select the same date, it reappears as "MM/DD/YYYY" format and allows me to save.

**Comment by sawprogramming** [comment]
Oops, side effect of a change I made to stop that off-by-one thing with the date. Added a fix.

**Comment by sawprogramming** [comment]
Added in the new version. Please let me know of any issues!

**Comment by RaefWolfe** [comment]
It's fixed, but now the three loading bars appear underneath the date selector (rather than above it). I fixed on my end by giving it a z-index; not sure if it's a problem on others' versions as well.
